apiVersion: v1
kind: ConfigMap
metadata:
  name: htpasswd-config
  namespace: dev
data:
  htpasswd: |
    admin:$2y$05$xVuZil3DEQ3eHNGw/OTN1.bEut/N15IQUDXkWTXch10CqDYHe.IDW
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deployment
  namespace: dev
spec:
  selector:
    matchLabels:
      app: "registry"
  replicas: 1
  template:
    metadata:
      labels:
        app: "registry"
    spec:
      containers:
      - env:
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /data
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"
        - name: REGISTRY_AUTH
          value: htpasswd
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: Registry Realm
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: /auth/htpasswd
        image: registry:2
        volumeMounts:
          - name: registry-storage
            mountPath: /data
          - name: htpasswd-configs
            mountPath: /auth/
        imagePullPolicy: Always
        name: "registry"
        ports:
        - containerPort: 5000
          protocol: TCP
      volumes:
        - name: registry-storage
          persistentVolumeClaim:
            claimName: registry-data
        - name: htpasswd-configs
          configMap:
            name: htpasswd-config
---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: dev
  labels:
    app: servicelabel
spec:
  type: ClusterIP
  ports:
    - port: 5000
  selector:
    app: "registry"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry-ingress
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 10000m
spec:
  ingressClassName: nginx
  rules:
    - host: registry.labdevops.one
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: registry-service
                port:
                  number: 5000
            path: /

