apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-data
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 30Gi

