apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sonar.fullname" . }}
  labels:
    {{- include "sonar.labels" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
    - host: tools.labdevops.one
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: {{ include "sonar.fullname" . }}
                port:
                  number: 9000
            path: /sonar